//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atomex {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Atomex.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Address not found in local database.
        /// </summary>
        internal static string AddressNotFoundInLocalDb {
            get {
                return ResourceManager.GetString("AddressNotFoundInLocalDb", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to EnumerationValue must be of Enum type.
        /// </summary>
        internal static string EnumerationValueMustBeOfEnumType
        {
            get
            {
                return ResourceManager.GetString("EnumerationValueMustBeOfEnumType", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на &apos;From&apos; address must not be empty.
        /// </summary>
        internal static string FromAddressIsNullOrEmpty {
            get {
                return ResourceManager.GetString("FromAddressIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Insufficient funds.
        /// </summary>
        internal static string InsufficientFunds {
            get {
                return ResourceManager.GetString("InsufficientFunds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Insufficient funds. {0} {1} available.
        /// </summary>
        internal static string InsufficientFundsDetails {
            get {
                return ResourceManager.GetString("InsufficientFundsDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Insufficient funds to cover fees.
        /// </summary>
        internal static string InsufficientFundsToCoverFees {
            get {
                return ResourceManager.GetString("InsufficientFundsToCoverFees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Insufficient funds to cover fees. {0} {1} required. {2} {1} available.
        /// </summary>
        internal static string InsufficientFundsToCoverFeesDetails {
            get {
                return ResourceManager.GetString("InsufficientFundsToCoverFeesDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Insufficient funds to cover maker network fees.
        /// </summary>
        internal static string InsufficientFundsToCoverMakerNetworkFee {
            get {
                return ResourceManager.GetString("InsufficientFundsToCoverMakerNetworkFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Insufficient funds to cover maker network fees. {0} {1} required. {2} {1} available.
        /// </summary>
        internal static string InsufficientFundsToCoverMakerNetworkFeeDetails {
            get {
                return ResourceManager.GetString("InsufficientFundsToCoverMakerNetworkFeeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Insufficient funds. {0} {1} required. {2} {1} available.
        /// </summary>
        internal static string InsufficientFundsToSendAmountDetails {
            get {
                return ResourceManager.GetString("InsufficientFundsToSendAmountDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Too low fees.
        /// </summary>
        internal static string TooLowFees {
            get {
                return ResourceManager.GetString("TooLowFees", resourceCulture);
            }
        }
    }
}
